// Regenerates prototype/i18n.js from the real app, so the prototype shows the app's own Thai / Burmese / English labels.
// Run from the app folder:   cd app && node --experimental-strip-types --no-warnings ../prototype/make-i18n.mjs
import fs from "node:fs";
const { DICT } = await import("../app/src/modules/diner/i18n.ts");
const { ALLERGENS, ALLERGEN_LABEL, allergenName } = await import("../app/src/modules/platform/constants.ts");
const out = {
  dict: DICT,
  allergens: ALLERGENS,
  allergenNames: Object.fromEntries(["en", "th", "my"].map((l) => [l, Object.fromEntries(ALLERGENS.map((a) => [a, l === "en" ? ALLERGEN_LABEL[a] : allergenName(a, l)]))])),
};
fs.writeFileSync(new URL("./i18n.js", import.meta.url), `// GENERATED by make-i18n.mjs from app/src/modules/diner/i18n.ts and platform/constants.ts. Do not edit by hand.\nwindow.I18N = ${JSON.stringify(out, null, 1)};\n`);
console.log("wrote prototype/i18n.js");
